use std::sync::Arc;

use futures::{StreamExt, future::join_all};
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;
use tracing::warn;

use anie_protocol::{
    AgentEvent, AssistantMessage, ContentBlock, Message, StopReason, StreamDelta, ToolCall,
    ToolResult, ToolResultMessage, now_millis,
};
use anie_provider::{
    LlmContext, Model, ProviderError, ProviderEvent, ProviderRegistry, ProviderStream,
    RequestOptionsResolver, ThinkingLevel,
};

use crate::{
    AfterToolCallHook, BeforeToolCallHook, BeforeToolCallResult, ToolRegistry, ToolResultOverride,
};

/// Agent-loop execution mode for tool calls.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToolExecutionMode {
    /// Run one tool at a time.
    Sequential,
    /// Run all tool calls for the turn concurrently.
    Parallel,
}

/// Immutable configuration for an agent loop instance.
pub struct AgentLoopConfig {
    /// Selected model.
    pub model: Model,
    /// Final system prompt.
    pub system_prompt: String,
    /// Requested thinking level.
    pub thinking: ThinkingLevel,
    /// Tool execution strategy.
    pub tool_execution: ToolExecutionMode,
    /// Per-request auth/options resolver.
    pub request_options_resolver: Arc<dyn RequestOptionsResolver>,
    /// Optional steering-message hook.
    pub get_steering_messages: Option<Arc<dyn Fn() -> Vec<Message> + Send + Sync>>,
    /// Optional follow-up-message hook.
    pub get_follow_up_messages: Option<Arc<dyn Fn() -> Vec<Message> + Send + Sync>>,
    /// Optional before-tool-call hook.
    pub before_tool_call_hook: Option<Arc<dyn BeforeToolCallHook>>,
    /// Optional after-tool-call hook.
    pub after_tool_call_hook: Option<Arc<dyn AfterToolCallHook>>,
}

/// Final agent-run output.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct AgentRunResult {
    /// Messages generated by the assistant/tool loop (not including prompts).
    pub generated_messages: Vec<Message>,
    /// Final canonical context including prompts and generated messages.
    pub final_context: Vec<Message>,
    /// Structured terminal provider error, if the run ended with one.
    pub terminal_error: Option<ProviderError>,
}

/// The core provider/tool-agnostic agent loop.
pub struct AgentLoop {
    provider_registry: Arc<ProviderRegistry>,
    tool_registry: Arc<ToolRegistry>,
    config: AgentLoopConfig,
}

impl AgentLoop {
    /// Create a new agent loop.
    #[must_use]
    pub fn new(
        provider_registry: Arc<ProviderRegistry>,
        tool_registry: Arc<ToolRegistry>,
        config: AgentLoopConfig,
    ) -> Self {
        Self {
            provider_registry,
            tool_registry,
            config,
        }
    }

    /// Run the agent loop using owned prompt and context state.
    pub async fn run(
        &self,
        prompts: Vec<Message>,
        context: Vec<Message>,
        event_tx: mpsc::Sender<AgentEvent>,
        cancel: CancellationToken,
    ) -> AgentRunResult {
        let mut context = context;
        let mut generated_messages = Vec::new();
        context.extend(prompts.iter().cloned());

        let _ = event_tx.send(AgentEvent::AgentStart).await;
        let _ = event_tx.send(AgentEvent::TurnStart).await;

        for prompt in &prompts {
            let _ = event_tx
                .send(AgentEvent::MessageStart {
                    message: prompt.clone(),
                })
                .await;
            let _ = event_tx
                .send(AgentEvent::MessageEnd {
                    message: prompt.clone(),
                })
                .await;
        }

        loop {
            let request = match self
                .config
                .request_options_resolver
                .resolve(&self.config.model, &context)
                .await
            {
                Ok(request) => request,
                Err(error) => {
                    let assistant =
                        self.error_assistant_message(error.to_string(), StopReason::Error);
                    self.finish_with_assistant(
                        assistant,
                        &mut context,
                        &mut generated_messages,
                        &event_tx,
                        Vec::new(),
                    )
                    .await;
                    return AgentRunResult {
                        generated_messages,
                        final_context: context,
                        terminal_error: Some(error),
                    };
                }
            };

            let provider = match self.provider_registry.get(&self.config.model.api) {
                Some(provider) => provider,
                None => {
                    let assistant = self.error_assistant_message(
                        format!("No provider registered for {:?}", self.config.model.api),
                        StopReason::Error,
                    );
                    self.finish_with_assistant(
                        assistant,
                        &mut context,
                        &mut generated_messages,
                        &event_tx,
                        Vec::new(),
                    )
                    .await;
                    return AgentRunResult {
                        generated_messages,
                        final_context: context,
                        terminal_error: None,
                    };
                }
            };

            let mut model = self.config.model.clone();
            if let Some(base_url_override) = request.base_url_override {
                model.base_url = base_url_override;
            }

            let llm_context = LlmContext {
                system_prompt: self.config.system_prompt.clone(),
                messages: provider.convert_messages(&context),
                tools: self.tool_registry.definitions(),
            };
            let options = anie_provider::StreamOptions {
                api_key: request.api_key,
                temperature: None,
                max_tokens: Some(model.max_tokens),
                thinking: self.config.thinking,
                headers: request.headers,
            };

            let stream = match provider.stream(&model, llm_context, options) {
                Ok(stream) => stream,
                Err(error) => {
                    let assistant =
                        self.error_assistant_message(error.to_string(), StopReason::Error);
                    self.finish_with_assistant(
                        assistant,
                        &mut context,
                        &mut generated_messages,
                        &event_tx,
                        Vec::new(),
                    )
                    .await;
                    return AgentRunResult {
                        generated_messages,
                        final_context: context,
                        terminal_error: Some(error),
                    };
                }
            };

            let collected = self.collect_stream(stream, &event_tx, &cancel).await;
            let assistant = collected.assistant;
            let assistant_message = Message::Assistant(assistant.clone());
            context.push(assistant_message.clone());
            generated_messages.push(assistant_message);

            if collected.provider_error.is_some()
                || matches!(
                    assistant.stop_reason,
                    StopReason::Error | StopReason::Aborted
                )
            {
                let _ = event_tx
                    .send(AgentEvent::TurnEnd {
                        assistant,
                        tool_results: Vec::new(),
                    })
                    .await;
                let _ = event_tx
                    .send(AgentEvent::AgentEnd {
                        messages: generated_messages.clone(),
                    })
                    .await;
                return AgentRunResult {
                    generated_messages,
                    final_context: context,
                    terminal_error: collected.provider_error,
                };
            }

            let tool_calls = extract_tool_calls(&assistant);
            if tool_calls.is_empty() {
                if let Some(get_follow_up_messages) = &self.config.get_follow_up_messages {
                    let follow_up_messages = get_follow_up_messages();
                    if !follow_up_messages.is_empty() {
                        context.extend(follow_up_messages);
                        let _ = event_tx
                            .send(AgentEvent::TurnEnd {
                                assistant,
                                tool_results: Vec::new(),
                            })
                            .await;
                        let _ = event_tx.send(AgentEvent::TurnStart).await;
                        continue;
                    }
                }

                let _ = event_tx
                    .send(AgentEvent::TurnEnd {
                        assistant,
                        tool_results: Vec::new(),
                    })
                    .await;
                let _ = event_tx
                    .send(AgentEvent::AgentEnd {
                        messages: generated_messages.clone(),
                    })
                    .await;
                return AgentRunResult {
                    generated_messages,
                    final_context: context,
                    terminal_error: None,
                };
            }

            let tool_results = self
                .execute_tool_calls(&tool_calls, &context, &event_tx, &cancel)
                .await;

            for tool_result in &tool_results {
                let message = Message::ToolResult(tool_result.clone());
                context.push(message.clone());
                generated_messages.push(message);
            }

            if let Some(get_steering_messages) = &self.config.get_steering_messages {
                context.extend(get_steering_messages());
            }

            let _ = event_tx
                .send(AgentEvent::TurnEnd {
                    assistant,
                    tool_results: tool_results.clone(),
                })
                .await;

            if cancel.is_cancelled() {
                let _ = event_tx
                    .send(AgentEvent::AgentEnd {
                        messages: generated_messages.clone(),
                    })
                    .await;
                return AgentRunResult {
                    generated_messages,
                    final_context: context,
                    terminal_error: None,
                };
            }

            let _ = event_tx.send(AgentEvent::TurnStart).await;
        }
    }

    async fn finish_with_assistant(
        &self,
        assistant: AssistantMessage,
        context: &mut Vec<Message>,
        generated_messages: &mut Vec<Message>,
        event_tx: &mpsc::Sender<AgentEvent>,
        tool_results: Vec<ToolResultMessage>,
    ) {
        let message = Message::Assistant(assistant.clone());
        let _ = event_tx
            .send(AgentEvent::MessageStart {
                message: message.clone(),
            })
            .await;
        let _ = event_tx
            .send(AgentEvent::MessageEnd {
                message: message.clone(),
            })
            .await;
        context.push(message.clone());
        generated_messages.push(message);
        let _ = event_tx
            .send(AgentEvent::TurnEnd {
                assistant,
                tool_results,
            })
            .await;
        let _ = event_tx
            .send(AgentEvent::AgentEnd {
                messages: generated_messages.clone(),
            })
            .await;
    }

    async fn collect_stream(
        &self,
        stream: ProviderStream,
        event_tx: &mpsc::Sender<AgentEvent>,
        cancel: &CancellationToken,
    ) -> CollectedAssistant {
        let mut builder = AssistantMessageBuilder::new(
            self.config.model.provider.clone(),
            self.config.model.id.clone(),
        );
        let placeholder = Message::Assistant(builder.placeholder_message());
        let _ = event_tx
            .send(AgentEvent::MessageStart {
                message: placeholder,
            })
            .await;

        tokio::pin!(stream);
        let mut active_delta = None;

        loop {
            tokio::select! {
                _ = cancel.cancelled() => {
                    self.finish_active_delta(event_tx, &mut active_delta).await;
                    let assistant = builder.finish(StopReason::Aborted, Some("Run aborted".into()));
                    let _ = event_tx.send(AgentEvent::MessageEnd { message: Message::Assistant(assistant.clone()) }).await;
                    return CollectedAssistant {
                        assistant,
                        provider_error: None,
                    };
                }
                event = stream.next() => {
                    match event {
                        Some(Ok(provider_event)) => match provider_event {
                            ProviderEvent::Start => {}
                            ProviderEvent::TextDelta(text) => {
                                self.start_delta_if_needed(event_tx, &mut active_delta, ActiveDelta::Text).await;
                                builder.push_text(&text);
                                let _ = event_tx.send(AgentEvent::MessageDelta { delta: StreamDelta::TextDelta(text) }).await;
                            }
                            ProviderEvent::ThinkingDelta(thinking) => {
                                self.start_delta_if_needed(event_tx, &mut active_delta, ActiveDelta::Thinking).await;
                                builder.push_thinking(&thinking);
                                let _ = event_tx.send(AgentEvent::MessageDelta { delta: StreamDelta::ThinkingDelta(thinking) }).await;
                            }
                            ProviderEvent::ToolCallStart(tool_call) => {
                                self.finish_active_delta(event_tx, &mut active_delta).await;
                                builder.start_tool_call(tool_call.clone());
                                let _ = event_tx.send(AgentEvent::MessageDelta { delta: StreamDelta::ToolCallStart(tool_call) }).await;
                            }
                            ProviderEvent::ToolCallDelta { id, arguments_delta } => {
                                builder.append_tool_call_delta(&id, &arguments_delta);
                                let _ = event_tx.send(AgentEvent::MessageDelta {
                                    delta: StreamDelta::ToolCallDelta {
                                        id,
                                        arguments_delta,
                                    },
                                }).await;
                            }
                            ProviderEvent::ToolCallEnd { id } => {
                                builder.finish_tool_call(&id);
                                let _ = event_tx.send(AgentEvent::MessageDelta {
                                    delta: StreamDelta::ToolCallEnd { id },
                                }).await;
                            }
                            ProviderEvent::Done(message) => {
                                self.finish_active_delta(event_tx, &mut active_delta).await;
                                let _ = event_tx.send(AgentEvent::MessageEnd { message: Message::Assistant(message.clone()) }).await;
                                return CollectedAssistant {
                                    assistant: message,
                                    provider_error: None,
                                };
                            }
                        },
                        Some(Err(error)) => {
                            self.finish_active_delta(event_tx, &mut active_delta).await;
                            let assistant = builder.finish(StopReason::Error, Some(error.to_string()));
                            let _ = event_tx.send(AgentEvent::MessageEnd { message: Message::Assistant(assistant.clone()) }).await;
                            return CollectedAssistant {
                                assistant,
                                provider_error: Some(error),
                            };
                        }
                        None => {
                            self.finish_active_delta(event_tx, &mut active_delta).await;
                            let error = ProviderError::Stream("Stream ended unexpectedly".into());
                            let assistant = builder.finish(StopReason::Error, Some(error.to_string()));
                            let _ = event_tx.send(AgentEvent::MessageEnd { message: Message::Assistant(assistant.clone()) }).await;
                            return CollectedAssistant {
                                assistant,
                                provider_error: Some(error),
                            };
                        }
                    }
                }
            }
        }
    }

    async fn start_delta_if_needed(
        &self,
        event_tx: &mpsc::Sender<AgentEvent>,
        active_delta: &mut Option<ActiveDelta>,
        next: ActiveDelta,
    ) {
        if *active_delta == Some(next) {
            return;
        }

        self.finish_active_delta(event_tx, active_delta).await;
        let delta = match next {
            ActiveDelta::Text => StreamDelta::TextStart,
            ActiveDelta::Thinking => StreamDelta::ThinkingStart,
        };
        let _ = event_tx.send(AgentEvent::MessageDelta { delta }).await;
        *active_delta = Some(next);
    }

    async fn finish_active_delta(
        &self,
        event_tx: &mpsc::Sender<AgentEvent>,
        active_delta: &mut Option<ActiveDelta>,
    ) {
        if let Some(delta_kind) = active_delta.take() {
            let delta = match delta_kind {
                ActiveDelta::Text => StreamDelta::TextEnd,
                ActiveDelta::Thinking => StreamDelta::ThinkingEnd,
            };
            let _ = event_tx.send(AgentEvent::MessageDelta { delta }).await;
        }
    }

    async fn execute_tool_calls(
        &self,
        tool_calls: &[ToolCall],
        context: &[Message],
        event_tx: &mpsc::Sender<AgentEvent>,
        cancel: &CancellationToken,
    ) -> Vec<ToolResultMessage> {
        match self.config.tool_execution {
            ToolExecutionMode::Sequential => {
                let mut results = Vec::with_capacity(tool_calls.len());
                for tool_call in tool_calls {
                    results.push(
                        self.execute_single_tool(tool_call.clone(), context, event_tx, cancel)
                            .await,
                    );
                }
                results
            }
            ToolExecutionMode::Parallel => {
                let futures = tool_calls.iter().cloned().map(|tool_call| {
                    self.execute_single_tool(tool_call, context, event_tx, cancel)
                });
                join_all(futures).await
            }
        }
    }

    async fn execute_single_tool(
        &self,
        tool_call: ToolCall,
        context: &[Message],
        event_tx: &mpsc::Sender<AgentEvent>,
        cancel: &CancellationToken,
    ) -> ToolResultMessage {
        let _ = event_tx
            .send(AgentEvent::ToolExecStart {
                call_id: tool_call.id.clone(),
                tool_name: tool_call.name.clone(),
                args: tool_call.arguments.clone(),
            })
            .await;

        let Some(tool) = self.tool_registry.get(&tool_call.name) else {
            let result = error_tool_result(format!("Tool not found: {}", tool_call.name));
            let _ = event_tx
                .send(AgentEvent::ToolExecEnd {
                    call_id: tool_call.id.clone(),
                    result: result.clone(),
                    is_error: true,
                })
                .await;
            return tool_result_message(&tool_call, result, true);
        };

        let definition = tool.definition();
        if let Err(message) = validate_tool_arguments(&definition.parameters, &tool_call.arguments)
        {
            let result = error_tool_result(message);
            let _ = event_tx
                .send(AgentEvent::ToolExecEnd {
                    call_id: tool_call.id.clone(),
                    result: result.clone(),
                    is_error: true,
                })
                .await;
            return tool_result_message(&tool_call, result, true);
        }

        if let Some(hook) = &self.config.before_tool_call_hook {
            match hook
                .before_tool_call(&tool_call, &tool_call.arguments, context)
                .await
            {
                BeforeToolCallResult::Allow => {}
                BeforeToolCallResult::Block { reason } => {
                    let result = error_tool_result(reason);
                    let _ = event_tx
                        .send(AgentEvent::ToolExecEnd {
                            call_id: tool_call.id.clone(),
                            result: result.clone(),
                            is_error: true,
                        })
                        .await;
                    return tool_result_message(&tool_call, result, true);
                }
            }
        }

        let (update_tx, mut update_rx) = mpsc::channel(16);
        let update_call_id = tool_call.id.clone();
        let update_event_tx = event_tx.clone();
        let update_forwarder = tokio::spawn(async move {
            while let Some(partial) = update_rx.recv().await {
                let _ = update_event_tx
                    .send(AgentEvent::ToolExecUpdate {
                        call_id: update_call_id.clone(),
                        partial,
                    })
                    .await;
            }
        });

        let execution = tool
            .execute(
                &tool_call.id,
                tool_call.arguments.clone(),
                cancel.child_token(),
                Some(update_tx),
            )
            .await;
        let _ = update_forwarder.await;

        let (mut result, mut is_error) = match execution {
            Ok(result) => (result, false),
            Err(error) => (error_tool_result(error.to_string()), true),
        };

        if let Some(hook) = &self.config.after_tool_call_hook {
            if let Some(override_result) = hook.after_tool_call(&tool_call, &result, is_error).await
            {
                apply_tool_result_override(&mut result, &mut is_error, override_result);
            }
        }

        attach_tool_invocation_details(&tool_call, &mut result.details);

        let _ = event_tx
            .send(AgentEvent::ToolExecEnd {
                call_id: tool_call.id.clone(),
                result: result.clone(),
                is_error,
            })
            .await;

        tool_result_message(&tool_call, result, is_error)
    }

    fn error_assistant_message(
        &self,
        error_message: String,
        stop_reason: StopReason,
    ) -> AssistantMessage {
        AssistantMessage {
            content: vec![ContentBlock::Text {
                text: error_message.clone(),
            }],
            usage: Default::default(),
            stop_reason,
            error_message: Some(error_message),
            provider: self.config.model.provider.clone(),
            model: self.config.model.id.clone(),
            timestamp: now_millis(),
        }
    }
}

fn extract_tool_calls(assistant: &AssistantMessage) -> Vec<ToolCall> {
    assistant
        .content
        .iter()
        .filter_map(|block| match block {
            ContentBlock::ToolCall(tool_call) => Some(tool_call.clone()),
            _ => None,
        })
        .collect()
}

fn validate_tool_arguments(
    schema: &serde_json::Value,
    args: &serde_json::Value,
) -> Result<(), String> {
    let validator = jsonschema::validator_for(schema)
        .map_err(|error| format!("Tool schema compilation failed: {error}"))?;
    let errors: Vec<String> = validator
        .iter_errors(args)
        .map(|error| error.to_string())
        .collect();
    if errors.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "Tool arguments failed validation: {}",
            errors.join("; ")
        ))
    }
}

fn error_tool_result(message: String) -> ToolResult {
    ToolResult {
        content: vec![ContentBlock::Text {
            text: message.clone(),
        }],
        details: serde_json::json!({ "error": message }),
    }
}

fn tool_result_message(
    tool_call: &ToolCall,
    result: ToolResult,
    is_error: bool,
) -> ToolResultMessage {
    ToolResultMessage {
        tool_call_id: tool_call.id.clone(),
        tool_name: tool_call.name.clone(),
        content: result.content,
        details: result.details,
        is_error,
        timestamp: now_millis(),
    }
}

fn apply_tool_result_override(
    result: &mut ToolResult,
    is_error: &mut bool,
    override_result: ToolResultOverride,
) {
    if let Some(content) = override_result.content {
        result.content = content;
    }
    if let Some(details) = override_result.details {
        result.details = details;
    }
    if let Some(override_is_error) = override_result.is_error {
        *is_error = override_is_error;
    }
}

fn attach_tool_invocation_details(tool_call: &ToolCall, details: &mut serde_json::Value) {
    if !details.is_object() {
        *details = serde_json::json!({});
    }

    let Some(map) = details.as_object_mut() else {
        return;
    };
    map.entry("tool_name")
        .or_insert_with(|| serde_json::Value::String(tool_call.name.clone()));
    if let Some(path) = tool_call.arguments.get("path").cloned() {
        map.entry("path").or_insert(path);
    }
    if let Some(command) = tool_call.arguments.get("command").cloned() {
        map.entry("command").or_insert(command);
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ActiveDelta {
    Text,
    Thinking,
}

struct CollectedAssistant {
    assistant: AssistantMessage,
    provider_error: Option<ProviderError>,
}

struct AssistantMessageBuilder {
    content: Vec<BuilderContent>,
    provider: String,
    model: String,
}

impl AssistantMessageBuilder {
    fn new(provider: String, model: String) -> Self {
        Self {
            content: Vec::new(),
            provider,
            model,
        }
    }

    fn placeholder_message(&self) -> AssistantMessage {
        AssistantMessage {
            content: Vec::new(),
            usage: Default::default(),
            stop_reason: StopReason::Stop,
            error_message: None,
            provider: self.provider.clone(),
            model: self.model.clone(),
            timestamp: now_millis(),
        }
    }

    fn push_text(&mut self, text: &str) {
        match self.content.last_mut() {
            Some(BuilderContent::Text(existing)) => existing.push_str(text),
            _ => self.content.push(BuilderContent::Text(text.to_string())),
        }
    }

    fn push_thinking(&mut self, thinking: &str) {
        match self.content.last_mut() {
            Some(BuilderContent::Thinking(existing)) => existing.push_str(thinking),
            _ => self
                .content
                .push(BuilderContent::Thinking(thinking.to_string())),
        }
    }

    fn start_tool_call(&mut self, tool_call: ToolCall) {
        self.content
            .push(BuilderContent::ToolCall(ToolCallBuilder::new(tool_call)));
    }

    fn append_tool_call_delta(&mut self, id: &str, arguments_delta: &str) {
        if let Some(tool_call) = self.find_tool_call_mut(id) {
            tool_call.arguments_buffer.push_str(arguments_delta);
        } else {
            warn!(
                tool_call_id = id,
                "received tool-call delta for unknown tool call"
            );
        }
    }

    fn finish_tool_call(&mut self, id: &str) {
        if let Some(tool_call) = self.find_tool_call_mut(id) {
            tool_call.finalize_arguments();
        }
    }

    fn finish(self, stop_reason: StopReason, error_message: Option<String>) -> AssistantMessage {
        let mut content: Vec<ContentBlock> = self
            .content
            .into_iter()
            .map(BuilderContent::into_content_block)
            .collect();
        if let Some(message) = &error_message
            && content.is_empty()
        {
            content.push(ContentBlock::Text {
                text: message.clone(),
            });
        }
        AssistantMessage {
            content,
            usage: Default::default(),
            stop_reason,
            error_message,
            provider: self.provider,
            model: self.model,
            timestamp: now_millis(),
        }
    }

    fn find_tool_call_mut(&mut self, id: &str) -> Option<&mut ToolCallBuilder> {
        self.content.iter_mut().find_map(|block| match block {
            BuilderContent::ToolCall(tool_call) if tool_call.id == id => Some(tool_call),
            _ => None,
        })
    }
}

enum BuilderContent {
    Text(String),
    Thinking(String),
    ToolCall(ToolCallBuilder),
}

impl BuilderContent {
    fn into_content_block(self) -> ContentBlock {
        match self {
            Self::Text(text) => ContentBlock::Text { text },
            Self::Thinking(thinking) => ContentBlock::Thinking { thinking },
            Self::ToolCall(tool_call) => ContentBlock::ToolCall(tool_call.into_tool_call()),
        }
    }
}

struct ToolCallBuilder {
    id: String,
    name: String,
    arguments_value: Option<serde_json::Value>,
    arguments_buffer: String,
}

impl ToolCallBuilder {
    fn new(tool_call: ToolCall) -> Self {
        Self {
            id: tool_call.id,
            name: tool_call.name,
            arguments_value: Some(tool_call.arguments),
            arguments_buffer: String::new(),
        }
    }

    fn finalize_arguments(&mut self) {
        if self.arguments_buffer.is_empty() {
            return;
        }

        match serde_json::from_str(&self.arguments_buffer) {
            Ok(arguments) => self.arguments_value = Some(arguments),
            Err(error) => {
                self.arguments_value = Some(serde_json::json!({
                    "_raw": self.arguments_buffer,
                    "_error": error.to_string(),
                }));
            }
        }
    }

    fn into_tool_call(mut self) -> ToolCall {
        self.finalize_arguments();
        ToolCall {
            id: self.id,
            name: self.name,
            arguments: self.arguments_value.unwrap_or(serde_json::Value::Null),
        }
    }
}
